#게시판 정보 테이블
CREATE TABLE BOARD (
	BOARD_NUM INT PRIMARY KEY AUTO_INCREMENT
	, TITLE VARCHAR(30) NOT NULL
	, WRITER VARCHAR(30) NOT NULL
	, CONTENT VARCHAR(30)
	, READ_CNT INT DEFAULT 0
	, REG_DATE DATETIME DEFAULT SYSDATE()
);

CREATE TABLE BOARD_REPLY (
	REPLY_NUM INT PRIMARY KEY AUTO_INCREMENT
	, CONTENT VARCHAR(30) NOT NULL
	, WRITER VARCHAR(20) NOT NULL
	, REG_DATE DATETIME DEFAULT SYSDATE()
	, BOARD_NUM INT NOT NULL REFERENCES BOARD (BOARD_NUM)
);

INSERT INTO BOARD
VALUES
(1, '첫 번째 글', '김자바', '첫번째', 5, '2021-01-21 10:22:50'),
(2, '두 번째 글', '이자바', '두번째', 3, '2021-03-05 10:22:50'),
(3, '세 번째 글', '김자바', '세번째', 1, '2021-05-06 10:22:50'),
(4, '제목입니다', '홍길동', '네번째', 2, '2021-08-10 10:22:50'),
(5, '안녕하세요', '임꺽정', '다섯번째', 7, '2021-09-15 10:22:50');



INSERT INTO BOARD_REPLY VALUES(1, 'AA', 'BB', NOW(), 5);
DROP TABLE board_reply;



SELECT * FROM board;
SELECT * FROM BOARD_REPLY;
COMMIT;



SELECT *
FROM board
WHERE TITLE LIKE '%#{searcgValue}%';

SELECT *
FROM board
WHERE WRITER LIKE '%{}%';






















