#상품정보 테이블 
CREATE TABLE ITEM_INFO(
	ITEM_NUM INT PRIMARY KEY AUTO_INCREMENT 
	, ITEM_NAME VARCHAR(20) NOT NULL UNIQUE
	, ITEM_PRICE INT NOT NULL
	, SELLER VARCHAR(10)
	, ITEM_INTRO VARCHAR(20)
	, REG_DATE DATETIME DEFAULT SYSDATE()
);


#주문정보 테이블
CREATE TABLE order_info(
	ORDER_NUM INT PRIMARY KEY AUTO_INCREMENT
	, ITEM_NUM INT NOT NULL REFERENCES ITEM_INFO (ITEM_NUM) #상품번호
	, BUYER VARCHAR(20) NOT NULL
	, BUY_CNT INT NOT NULL
	, BUY_PRICE INT NOT NULL
	, BUY_DATE DATETIME DEFAULT SYSDATE()
);

SELECT * FROM item_info;
COMMIT;

SELECT * FROM emp;
SELECT * FROM dept;
SELECT * FROM order_info;
SELECT * FROM board;
DESC board;
SELECT * FROM board_reply;

# BOARD_REPLY 테이블의 컬럼 변경
ALTER TABLE board_reply CHANGE COLUMN CONTENT REPLY_CONTENT VARCHAR(20);
ALTER TABLE board_reply CHANGE COLUMN WRITER REPLY_WRITER VARCHAR(20);
ALTER TABLE board_reply CHANGE COLUMN REG_DATE REPLY_REG_DATE DATETIME DEFAULT SYSDATE();

# 모든 게시글의 게시글번호, 제목, 작성자 및 게시글에 달린 댓글 내용, 댓글 작성자를 조회
SELECT B.BOARD_NUM, TITLE, WRITER, REPLY_CONTENT, REPLY_WRITER
FROM board B INNER JOIN board_reply R
ON B.BOARD_NUM = R.BOARD_NUM;

# 모든 사원의 사번, 사원명, 급여, 부서번호, 부서명을 조회
SELECT EMPNO, ENAME, SAL, EMP.DEPTNO, DNAME, LOC
FROM emp INNER JOIN dept
ON emp.DEPTNO = dept.DEPTNO;


SELECT
      O.ITEM_NUM
      , ITEM_NAME
      , ITEM_PRICE
      , BUY_CNT
      , BUY_PRICE
      , BUYER
      , BUY_DATE
    FROM ORDER_INFO O INNER JOIN ITEM_INFO I
    ON O.ITEM_NUM = I.ITEM_NUM;
