
# 회원 테이블
CREATE TABLE REACT_MEMBER(
	MEM_ID VARCHAR(10) PRIMARY KEY
	, MEM_NAME VARCHAR(10) NOT NULL
	, MEM_PW VARCHAR(10) NOT NULL
	, MEM_TEL VARCHAR(15) UNIQUE
	, MEM_INTRO VARCHAR(30) 
	, JOIN_DATE DATETIME DEFAULT SYSDATE()
);

INSERT INTO REACT_MEMBER 
VALUES ('kim', '이순신', '1234', '010-1111-2222', '안녕하세요', NOW());
COMMIT;

SELECT * FROM react_member;

DROP TABLE board;