
# 쇼핑몰 프로젝트 테이블

# 상품 카테고리 테이블(소설, 자기계발...)
CREATE TABLE BOOK_CATEGORY (
	CATE_CODE INT PRIMARY KEY AUTO_INCREMENT 	#카테고리 코드
	, CATE_NAME VARCHAR(30) NOT NULL UNIQUE	#카테고리 이름
);

INSERT INTO BOOK_CATEGORY VALUES (1, 'IT/인터넷');
INSERT INTO BOOK_CATEGORY VALUES (2, '소설');
INSERT INTO BOOK_CATEGORY VALUES (3, '자기계발');
COMMIT;
SELECT * FROM book_category;
SELECT * FROM book;

# 도서 테이블
CREATE TABLE BOOK(
	BOOK_CODE INT PRIMARY KEY AUTO_INCREMENT
	, BOOK_NAME VARCHAR(30) NOT NULL
	, BOOK_PRICE INT NOT NULL
	, PUBLISHER VARCHAR(30) NOT NULL
	, BOOK_INFO VARCHAR(100)
	, REGDATE DATETIME DEFAULT SYSDATE()
	, BOOK_STOCK INT DEFAULT 10 
	, CATE_CODE INT NOT NULL REFERENCES book_category (CATE_CODE)
);

# 쇼핑몰 회원 테이블
CREATE TABLE SHOP_USER(
	USER_ID VARCHAR(30) PRIMARY KEY
	, USER_PW VARCHAR(30) NOT NULL
	, USER_NAME VARCHAR(10) NOT NULL
	, USER_EMAIL VARCHAR(30)
	, USER_TEL VARCHAR(16) NOT NULL UNIQUE
	, USER_ROLL VARCHAR(10) DEFAULT 'USER'		#권한 : USER-사용자, ADMIN-관리자
	, IS_USING VARCHAR(10) DEFAULT 'Y'			#상태 : Y - 사용 중, N - 탈퇴
	, JOIN_DATE DATETIME DEFAULT SYSDATE()
);





SELECT *
FROM BOOK_CATEGORY
WHERE CATE_NAME ='소설';

